// Generated by CoffeeScript 1.10.0
(function() {
  describe("UNIT: app.directive", function() {
    var $body, $compile, $el, $rootScope, $scope, el, simpleHtml;
    $rootScope = null;
    $scope = null;
    $compile = null;
    el = null;
    $el = null;
    $body = $('body');
    simpleHtml = "<the-directive></the-directive>";
    beforeEach(function() {
      module('app.directive', 'templates');
      inject(function($injector) {
        $rootScope = $injector.get("$rootScope");
        $compile = $injector.get("$compile");
        $scope = $rootScope.$new();
        el = $compile(angular.element(simpleHtml))($scope);
      });
      $body.append(el);
      $rootScope.$digest();
      $el = $("#bloc");
    });
    afterEach(function() {
      $body.empty();
    });
    it("should render the directive out in the DOM", function() {
      expect($el.length).toEqual(1);
    });
    it("should show the title", function() {
      expect($el.find("#title").text()).toEqual("appCtrl title");
    });
    describe("test title modification", function() {
      var ctrl;
      ctrl = null;
      beforeEach(function() {});
    });
  });

}).call(this);

//# sourceMappingURL=app.directive.spec.js.map
