// Generated by CoffeeScript 1.10.0
(function() {
  describe("UNIT: app.service", function() {
    var appService;
    appService = null;
    beforeEach(module("app.service"));
    beforeEach(inject(function($injector) {
      appService = $injector.get("AppService");
    }));
    it("should exist", function() {
      expect(appService).toBeDefined();
    });
    it("should calculate max of two numbers", function() {
      var result;
      result = appService.max(2, 5);
      expect(result).toEqual(5);
    });
    it("should return message if numbers are equal", function() {
      var result;
      result = appService.max(3, 3);
      expect(result).toEqual("Same numbers");
    });
  });

}).call(this);

//# sourceMappingURL=app.service.spec.js.map
