// Generated by CoffeeScript 1.10.0
(function() {
  describe("UNIT: app.directive", function() {
    var element;
    element = null;
    beforeEach(module("app.directive"));
    beforeEach(module("app.template.html"));
    beforeEach(inject(function($compile, $rootScope) {
      var scope;
      scope = $rootScope.$new();
      scope.size = 50;
      element = angular.element("<the-directive size='30'></the-directive>");
      $compile(element)(scope);
      scope.$digest();
    }));
    it("should display THE DIRECTIVE message ", function() {
      expect(element.html()).toMatch(/THE DIRECTIVE/);
    });
  });

}).call(this);

//# sourceMappingURL=app.directive.spec.js.map
